
server.port=8086
spring.application.name=audit-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://mongodb:27017/auditdb


# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=audit-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.max-poll-records=500

# Kafka Consumer Concurrency
spring.kafka.listener.concurrency=3

# Logging
logging.level.com.example.audit=INFO
logging.level.org.springframework.kafka=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Actuator
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
