package com.example.common.ai.agents;

import com.example.common.ai.AgentDecision;
import com.example.common.ai.BaseAgent;
import com.example.common.event.UserCreatedEvent;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.util.*;

/**
 * Jira Intelligence Agent - AI-powered Jira ticket management
 * Automatically generates, prioritizes, and routes tickets based on user events
 */
@Component
public class JiraIntelligenceAgent extends BaseAgent {
    
    public JiraIntelligenceAgent() {
        super("JiraIntelligenceAgent");
    }
    
    @Override
    protected AgentDecision executeDecisionLogic(Object input) {
        if (!(input instanceof TicketRequest)) {
            return createErrorDecision("Invalid input type, expected TicketRequest");
        }
        
        TicketRequest request = (TicketRequest) input;
        
        // AI-powered ticket generation
        JiraTicket ticket = generateIntelligentTicket(request);
        
        // Determine action and confidence
        String action = "CREATE_TICKET";
        double confidence = calculateConfidence(request, ticket);
        String reasoning = buildReasoning(ticket);
        
        AgentDecision decision = new AgentDecision(name, action, confidence, reasoning);
        decision.addParameter("ticket", ticket);
        decision.addParameter("priority", ticket.getPriority());
        decision.addParameter("assignee", ticket.getSuggestedAssignee());
        decision.addParameter("estimatedEffort", ticket.getEstimatedEffort());
        decision.setRequiresHumanApproval(ticket.getPriority().equals("Critical"));
        
        logger.info("🎫 Generated Jira ticket: {} - Priority: {}, Assignee: {}", 
                ticket.getTitle(), ticket.getPriority(), ticket.getSuggestedAssignee());
        
        return decision;
    }
    
    private JiraTicket generateIntelligentTicket(TicketRequest request) {
        JiraTicket ticket = new JiraTicket();
        
        // AI-powered title generation
        ticket.setTitle(generateTitle(request));
        
        // AI-powered description generation
        ticket.setDescription(generateDescription(request));
        
        // Intelligent priority assignment
        ticket.setPriority(determinePriority(request));
        
        // Smart assignee suggestion
        ticket.setSuggestedAssignee(suggestAssignee(request));
        
        // Effort estimation
        ticket.setEstimatedEffort(estimateEffort(request));
        
        // Labels and tags
        ticket.setLabels(generateLabels(request));
        
        // Set metadata
        ticket.setCreatedAt(LocalDateTime.now());
        ticket.setIssueType(determineIssueType(request));
        ticket.setComponent(determineComponent(request));
        
        return ticket;
    }
    
    private String generateTitle(TicketRequest request) {
        String type = request.getType();
        String context = request.getContext();
        
        switch (type) {
            case "USER_ANOMALY":
                return String.format("Investigate Suspicious User Activity - %s", 
                        request.getUserIdentifier());
            case "SERVICE_FAILURE":
                return String.format("Service Failure in %s - Requires Investigation", 
                        context);
            case "PERFORMANCE_ISSUE":
                return String.format("Performance Degradation Detected - %s", context);
            case "DATA_QUALITY":
                return String.format("Data Quality Issue - %s", request.getUserIdentifier());
            default:
                return String.format("Automated Issue Detection - %s", context);
        }
    }
    
    private String generateDescription(TicketRequest request) {
        StringBuilder description = new StringBuilder();
        
        description.append("*Automatically generated by AI Agent*\n\n");
        description.append("h3. Issue Summary\n");
        description.append(request.getDescription()).append("\n\n");
        
        description.append("h3. Detection Details\n");
        description.append("* Detection Time: ").append(LocalDateTime.now()).append("\n");
        description.append("* Detection Source: ").append(request.getSource()).append("\n");
        description.append("* Confidence Score: ").append(String.format("%.2f", request.getConfidence())).append("\n\n");
        
        if (request.getMetadata() != null && !request.getMetadata().isEmpty()) {
            description.append("h3. Additional Context\n");
            request.getMetadata().forEach((key, value) -> 
                    description.append("* ").append(key).append(": ").append(value).append("\n")
            );
        }
        
        description.append("\nh3. Recommended Actions\n");
        description.append(generateRecommendedActions(request));
        
        return description.toString();
    }
    
    private String determinePriority(TicketRequest request) {
        double confidence = request.getConfidence();
        String type = request.getType();
        
        // Critical: High confidence + security/service issues
        if (confidence >= 0.9 && (type.equals("USER_ANOMALY") || type.equals("SERVICE_FAILURE"))) {
            return "Critical";
        }
        
        // High: Medium-high confidence + important issues
        if (confidence >= 0.7 || type.equals("SERVICE_FAILURE")) {
            return "High";
        }
        
        // Medium: Moderate confidence or performance issues
        if (confidence >= 0.5 || type.equals("PERFORMANCE_ISSUE")) {
            return "Medium";
        }
        
        // Low: Everything else
        return "Low";
    }
    
    private String suggestAssignee(TicketRequest request) {
        String type = request.getType();
        
        // Simple rule-based assignment (can be enhanced with ML models)
        Map<String, String> assignmentRules = new HashMap<>();
        assignmentRules.put("USER_ANOMALY", "security-team");
        assignmentRules.put("SERVICE_FAILURE", "devops-team");
        assignmentRules.put("PERFORMANCE_ISSUE", "performance-team");
        assignmentRules.put("DATA_QUALITY", "data-team");
        
        return assignmentRules.getOrDefault(type, "triage-team");
    }
    
    private String estimateEffort(TicketRequest request) {
        String priority = determinePriority(request);
        
        switch (priority) {
            case "Critical":
                return "4-8 hours";
            case "High":
                return "2-4 hours";
            case "Medium":
                return "1-2 hours";
            default:
                return "< 1 hour";
        }
    }
    
    private List<String> generateLabels(TicketRequest request) {
        List<String> labels = new ArrayList<>();
        labels.add("ai-generated");
        labels.add(request.getType().toLowerCase().replace("_", "-"));
        labels.add("automated-detection");
        
        if (request.getConfidence() >= 0.8) {
            labels.add("high-confidence");
        }
        
        return labels;
    }
    
    private String determineIssueType(TicketRequest request) {
        if (request.getType().contains("ANOMALY")) {
            return "Security";
        } else if (request.getType().contains("FAILURE")) {
            return "Bug";
        } else if (request.getType().contains("PERFORMANCE")) {
            return "Performance";
        }
        return "Task";
    }
    
    private String determineComponent(TicketRequest request) {
        String context = request.getContext();
        if (context != null) {
            if (context.contains("evaluation")) return "evaluation-service";
            if (context.contains("sampling")) return "sampling-service";
            if (context.contains("evidence")) return "evidence-service";
            if (context.contains("remediation")) return "remediation-service";
            if (context.contains("jira")) return "jira-service";
        }
        return "platform";
    }
    
    private String generateRecommendedActions(TicketRequest request) {
        StringBuilder actions = new StringBuilder();
        String type = request.getType();
        
        switch (type) {
            case "USER_ANOMALY":
                actions.append("# Review user account details\n");
                actions.append("# Check recent activity logs\n");
                actions.append("# Verify email domain reputation\n");
                actions.append("# Consider account suspension if confirmed malicious\n");
                break;
            case "SERVICE_FAILURE":
                actions.append("# Check service logs for error details\n");
                actions.append("# Verify Kafka connectivity\n");
                actions.append("# Review recent deployments\n");
                actions.append("# Restart service if necessary\n");
                break;
            case "PERFORMANCE_ISSUE":
                actions.append("# Analyze performance metrics\n");
                actions.append("# Check database query performance\n");
                actions.append("# Review Kafka consumer lag\n");
                actions.append("# Consider scaling resources\n");
                break;
            default:
                actions.append("# Investigate issue details\n");
                actions.append("# Review relevant logs\n");
                actions.append("# Apply appropriate remediation\n");
        }
        
        return actions.toString();
    }
    
    private double calculateConfidence(TicketRequest request, JiraTicket ticket) {
        // Base confidence from request
        double confidence = request.getConfidence();
        
        // Adjust based on ticket characteristics
        if (ticket.getPriority().equals("Critical")) {
            confidence = Math.max(confidence, 0.9);
        }
        
        return Math.min(confidence, 1.0);
    }
    
    private String buildReasoning(JiraTicket ticket) {
        return String.format("Generated %s priority ticket for %s component, estimated effort: %s",
                ticket.getPriority(), ticket.getComponent(), ticket.getEstimatedEffort());
    }
    
    /**
     * Request object for ticket generation
     */
    public static class TicketRequest {
        private String type;
        private String description;
        private String context;
        private String userIdentifier;
        private String source;
        private double confidence;
        private Map<String, Object> metadata;
        
        public TicketRequest() {
            this.metadata = new HashMap<>();
        }
        
        public TicketRequest(String type, String description, String context, double confidence) {
            this();
            this.type = type;
            this.description = description;
            this.context = context;
            this.confidence = confidence;
        }
        
        // Getters and Setters
        public String getType() { return type; }
        public void setType(String type) { this.type = type; }
        
        public String getDescription() { return description; }
        public void setDescription(String description) { this.description = description; }
        
        public String getContext() { return context; }
        public void setContext(String context) { this.context = context; }
        
        public String getUserIdentifier() { return userIdentifier; }
        public void setUserIdentifier(String userIdentifier) { this.userIdentifier = userIdentifier; }
        
        public String getSource() { return source; }
        public void setSource(String source) { this.source = source; }
        
        public double getConfidence() { return confidence; }
        public void setConfidence(double confidence) { this.confidence = confidence; }
        
        public Map<String, Object> getMetadata() { return metadata; }
        public void setMetadata(Map<String, Object> metadata) { this.metadata = metadata; }
    }
    
    /**
     * Jira ticket representation
     */
    public static class JiraTicket {
        private String title;
        private String description;
        private String priority;
        private String suggestedAssignee;
        private String estimatedEffort;
        private List<String> labels;
        private LocalDateTime createdAt;
        private String issueType;
        private String component;
        
        public JiraTicket() {
            this.labels = new ArrayList<>();
        }
        
        // Getters and Setters
        public String getTitle() { return title; }
        public void setTitle(String title) { this.title = title; }
        
        public String getDescription() { return description; }
        public void setDescription(String description) { this.description = description; }
        
        public String getPriority() { return priority; }
        public void setPriority(String priority) { this.priority = priority; }
        
        public String getSuggestedAssignee() { return suggestedAssignee; }
        public void setSuggestedAssignee(String suggestedAssignee) { this.suggestedAssignee = suggestedAssignee; }
        
        public String getEstimatedEffort() { return estimatedEffort; }
        public void setEstimatedEffort(String estimatedEffort) { this.estimatedEffort = estimatedEffort; }
        
        public List<String> getLabels() { return labels; }
        public void setLabels(List<String> labels) { this.labels = labels; }
        
        public LocalDateTime getCreatedAt() { return createdAt; }
        public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
        
        public String getIssueType() { return issueType; }
        public void setIssueType(String issueType) { this.issueType = issueType; }
        
        public String getComponent() { return component; }
        public void setComponent(String component) { this.component = component; }
    }
}
